export const THERAPY_TOPICS = [
  "Abuse (Physical, Emotional, Sexual)",
  "Addiction & Substance Misuse",
  "Anger Management",
  "Anxiety & Panic Attacks",
  "Bereavement & Grief",
  "Body Image Issues",
  "Childhood Trauma",
  "Depression",
  "Domestic Violence",
  "Eating Disorders",
  "Family Conflicts",
  "Gender Identity Issues",
  "Health Anxiety",
  "Infidelity",
  "LGBTQ+ Issues",
  "Low Self-Esteem",
  "OCD (Obsessive Compulsive Disorder)",
  "Parenting Issues",
  "Phobias",
  "PTSD (Post-Traumatic Stress Disorder)",
  "Racial & Cultural Identity",
  "Relationship Issues",
  "Self-Harm",
  "Sexual Abuse/Assault",
  "Social Anxiety",
  "Stress Management",
  "Suicidal Ideation",
  "Work-Related Stress",
];

export const SUPPORT_AREAS = THERAPY_TOPICS;
