<?php

namespace Database\Seeders;

use App\Models\Client;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Str;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = [
            // Active Therapy Clients
            [
                'uuid' => Str::uuid(),
                'client_id' => 'CL001',
                'name' => 'Emma Wilson',
                'age' => 31,
                'email' => 'emma.w@email.com',
                'phone' => '+44 7700 900101',
                'address' => '123 High Street',
                'postcode' => 'SW1A 1AA',
                'gender' => 'Female',
                'ethnicity' => 'White British',
                'sexual_orientation' => 'Heterosexual',
                'stage' => 'Active Therapy',
                'status' => 'active',
                'service_type' => 'Low Cost',
                'primary_issues' => ['Anxiety', 'Work Stress'],
                'additional_details' => 'Experiencing burnout from work. Recently promoted to management role.',
                'medication' => 'Sertraline 50mg',
                'disabilities' => 'None',
                'risk_flags' => 'None',
                'substance_misuse' => 'None',
                'availability' => [
                    'Monday' => ['morning-early'],
                    'Tuesday' => [],
                    'Wednesday' => ['afternoon-early'],
                    'Thursday' => [],
                    'Friday' => ['morning-late']
                ],
                'submitted_date' => Carbon::parse('2025-02-15'),
                'start_date' => Carbon::parse('2025-02-28'),
                'sessions_completed' => 6,
                'matched_tc_id' => 1, // Sarah Johnson
                'matched_date' => Carbon::parse('2025-02-22'),
                'agreement_status' => 'signed',
                'agreement_signed_at' => Carbon::parse('2025-02-25'),
            ],
            [
                'uuid' => Str::uuid(),
                'client_id' => 'CL002',
                'name' => 'John Smith',
                'age' => 28,
                'email' => 'john.s@email.com',
                'phone' => '+44 7700 900102',
                'address' => '456 Park Road',
                'postcode' => 'M1 1AA',
                'gender' => 'Male',
                'ethnicity' => 'White British',
                'sexual_orientation' => 'Heterosexual',
                'stage' => 'Active Therapy',
                'status' => 'active',
                'service_type' => 'Low Cost',
                'primary_issues' => ['Depression', 'Relationship Issues'],
                'additional_details' => 'Struggling with relationship breakdown and low mood.',
                'medication' => 'None',
                'disabilities' => 'None',
                'risk_flags' => 'None',
                'substance_misuse' => 'None',
                'availability' => [
                    'Monday' => ['afternoon-early', 'evening'],
                    'Tuesday' => ['morning-early'],
                    'Wednesday' => [],
                    'Thursday' => ['afternoon-late', 'evening'],
                    'Friday' => []
                ],
                'submitted_date' => Carbon::parse('2025-01-20'),
                'start_date' => Carbon::parse('2025-02-01'),
                'sessions_completed' => 8,
                'matched_tc_id' => 2, // David Chen
                'matched_date' => Carbon::parse('2025-01-28'),
                'agreement_status' => 'signed',
                'agreement_signed_at' => Carbon::parse('2025-01-30'),
            ],
            [
                'uuid' => Str::uuid(),
                'client_id' => 'CL011',
                'name' => 'Michael Brown',
                'age' => 35,
                'email' => 'michael.b@email.com',
                'phone' => '+44 7700 900111',
                'address' => '789 Oak Avenue',
                'postcode' => 'B1 1AA',
                'gender' => 'Male',
                'ethnicity' => 'Black British',
                'sexual_orientation' => 'Heterosexual',
                'stage' => 'Active Therapy',
                'status' => 'active',
                'service_type' => 'Low Cost',
                'primary_issues' => ['Work Stress', 'Communication Problems'],
                'additional_details' => 'Having trouble communicating effectively at work.',
                'medication' => 'None',
                'disabilities' => 'None',
                'risk_flags' => 'None',
                'substance_misuse' => 'None',
                'availability' => [
                    'Monday' => ['morning-early', 'afternoon-early'],
                    'Tuesday' => ['morning-late', 'afternoon-early'],
                    'Wednesday' => ['morning-early'],
                    'Thursday' => [],
                    'Friday' => ['afternoon-late']
                ],
                'submitted_date' => Carbon::parse('2025-02-25'),
                'start_date' => Carbon::parse('2025-03-01'),
                'sessions_completed' => 4,
                'matched_tc_id' => 3, // Priya Patel
                'matched_date' => Carbon::parse('2025-02-27'),
                'agreement_status' => 'signed',
                'agreement_signed_at' => Carbon::parse('2025-02-28'),
            ],
            // Pending Match Clients
            [
                'uuid' => Str::uuid(),
                'client_id' => 'CL005',
                'name' => 'Charlotte Evans',
                'age' => 30,
                'email' => 'charlotte.e@email.com',
                'phone' => '+44 7700 900105',
                'address' => '321 Elm Street',
                'postcode' => 'L1 1AA',
                'gender' => 'Female',
                'ethnicity' => 'White British',
                'sexual_orientation' => 'Heterosexual',
                'stage' => 'Pending Match',
                'status' => 'urgent',
                'service_type' => 'Low Cost',
                'primary_issues' => ['Anxiety', 'Work Stress'],
                'additional_details' => 'High levels of work-related anxiety.',
                'medication' => 'None',
                'disabilities' => 'None',
                'risk_flags' => 'None',
                'substance_misuse' => 'None',
                'availability' => [
                    'Monday' => ['morning-early'],
                    'Tuesday' => [],
                    'Wednesday' => ['afternoon-early'],
                    'Thursday' => [],
                    'Friday' => ['morning-late']
                ],
                'submitted_date' => Carbon::parse('2025-03-10'),
            ],
            [
                'uuid' => Str::uuid(),
                'client_id' => 'CL006',
                'name' => 'Benjamin Clark',
                'age' => 24,
                'email' => 'benjamin.c@email.com',
                'phone' => '+44 7700 900106',
                'address' => '654 Pine Road',
                'postcode' => 'N1 1AA',
                'gender' => 'Male',
                'ethnicity' => 'Mixed Heritage',
                'sexual_orientation' => 'Gay',
                'stage' => 'Pending Match',
                'status' => 'active',
                'service_type' => 'Low Cost',
                'primary_issues' => ['Sexual Abuse', 'Low Self-esteem'],
                'additional_details' => 'Seeking support after traumatic experience.',
                'medication' => 'None',
                'disabilities' => 'None',
                'risk_flags' => 'Moderate',
                'substance_misuse' => 'None',
                'availability' => [
                    'Monday' => ['afternoon-early', 'evening'],
                    'Tuesday' => ['morning-early'],
                    'Wednesday' => [],
                    'Thursday' => ['afternoon-late', 'evening'],
                    'Friday' => []
                ],
                'submitted_date' => Carbon::parse('2025-03-12'),
            ],
            [
                'uuid' => Str::uuid(),
                'client_id' => 'CL009',
                'name' => 'Thomas Wright',
                'age' => 33,
                'email' => 'thomas.w@email.com',
                'phone' => '+44 7700 900109',
                'address' => '987 Maple Drive',
                'postcode' => 'S1 1AA',
                'gender' => 'Male',
                'ethnicity' => 'White British',
                'sexual_orientation' => 'Heterosexual',
                'stage' => 'Pending Match',
                'status' => 'active',
                'service_type' => 'Low Cost',
                'primary_issues' => ['Depression', 'Relationship Problems'],
                'additional_details' => 'Struggling with depression and relationship issues.',
                'medication' => 'Citalopram 20mg',
                'disabilities' => 'None',
                'risk_flags' => 'None',
                'substance_misuse' => 'None',
                'availability' => [
                    'Monday' => ['evening'],
                    'Tuesday' => ['afternoon-late', 'evening'],
                    'Wednesday' => ['evening'],
                    'Thursday' => ['evening'],
                    'Friday' => []
                ],
                'submitted_date' => Carbon::parse('2025-03-08'),
            ],
            [
                'uuid' => Str::uuid(),
                'client_id' => 'CL016',
                'name' => 'Lucas Brown',
                'age' => 26,
                'email' => 'lucas.b@email.com',
                'phone' => '+44 7700 900116',
                'address' => '147 Cedar Lane',
                'postcode' => 'LS1 1AA',
                'gender' => 'Male',
                'ethnicity' => 'White British',
                'sexual_orientation' => 'Heterosexual',
                'stage' => 'Pending Match',
                'status' => 'active',
                'service_type' => 'Mid Range',
                'primary_issues' => ['Anxiety', 'Panic Attacks'],
                'additional_details' => 'Experiencing frequent panic attacks.',
                'medication' => 'None',
                'disabilities' => 'None',
                'risk_flags' => 'None',
                'substance_misuse' => 'None',
                'availability' => [
                    'Monday' => ['morning-early'],
                    'Tuesday' => [],
                    'Wednesday' => [],
                    'Thursday' => [],
                    'Friday' => ['morning-late']
                ],
                'submitted_date' => Carbon::parse('2025-03-18'),
            ],
            [
                'uuid' => Str::uuid(),
                'client_id' => 'CL017',
                'name' => 'Emma Thompson',
                'age' => 28,
                'email' => 'emma.t@email.com',
                'phone' => '+44 7700 900117',
                'address' => '258 Birch Street',
                'postcode' => 'G1 1AA',
                'gender' => 'Female',
                'ethnicity' => 'White British',
                'sexual_orientation' => 'Heterosexual',
                'stage' => 'Pending Match',
                'status' => 'urgent',
                'service_type' => 'Low Cost',
                'primary_issues' => ['Trauma', 'PTSD', 'Anxiety'],
                'additional_details' => 'Seeking support for trauma-related symptoms.',
                'medication' => 'None',
                'disabilities' => 'None',
                'risk_flags' => 'Moderate',
                'substance_misuse' => 'None',
                'availability' => [
                    'Monday' => [],
                    'Tuesday' => [],
                    'Wednesday' => ['evening'],
                    'Thursday' => [],
                    'Friday' => ['evening']
                ],
                'submitted_date' => Carbon::parse('2025-03-13'),
            ],
            // Agreement Pending
            [
                'uuid' => Str::uuid(),
                'client_id' => 'CL020',
                'name' => 'Sophie Green',
                'age' => 29,
                'email' => 'sophie.g@email.com',
                'phone' => '+44 7700 900120',
                'address' => '369 Willow Way',
                'postcode' => 'E1 1AA',
                'gender' => 'Female',
                'ethnicity' => 'Asian British',
                'sexual_orientation' => 'Heterosexual',
                'stage' => 'Agreement Pending',
                'status' => 'active',
                'service_type' => 'Low Cost',
                'primary_issues' => ['Anxiety', 'Social Anxiety'],
                'additional_details' => 'Struggling with social anxiety.',
                'medication' => 'None',
                'disabilities' => 'None',
                'risk_flags' => 'None',
                'substance_misuse' => 'None',
                'availability' => [
                    'Monday' => ['morning-early', 'afternoon-early'],
                    'Tuesday' => ['morning-late', 'afternoon-early'],
                    'Wednesday' => ['morning-early'],
                    'Thursday' => [],
                    'Friday' => ['afternoon-late']
                ],
                'submitted_date' => Carbon::parse('2025-03-15'),
                'matched_tc_id' => 3, // Priya Patel
                'matched_date' => Carbon::parse('2025-03-17'),
                'agreement_status' => 'pending',
                'agreement_sent_at' => Carbon::parse('2025-03-17'),
            ],
            // Consultation Completed
            [
                'uuid' => Str::uuid(),
                'client_id' => 'CL021',
                'name' => 'Daniel Lee',
                'age' => 32,
                'email' => 'daniel.l@email.com',
                'phone' => '+44 7700 900121',
                'address' => '741 Ash Grove',
                'postcode' => 'M2 2AA',
                'gender' => 'Male',
                'ethnicity' => 'Chinese British',
                'sexual_orientation' => 'Heterosexual',
                'stage' => 'Consultation Completed',
                'status' => 'active',
                'service_type' => 'Low Cost',
                'primary_issues' => ['Depression', 'Low Self-esteem'],
                'additional_details' => 'Struggling with self-esteem issues.',
                'medication' => 'None',
                'disabilities' => 'None',
                'risk_flags' => 'None',
                'substance_misuse' => 'None',
                'availability' => [
                    'Monday' => ['afternoon-late'],
                    'Tuesday' => ['morning-early', 'morning-late'],
                    'Wednesday' => ['afternoon-early'],
                    'Thursday' => ['morning-late'],
                    'Friday' => ['morning-early']
                ],
                'submitted_date' => Carbon::parse('2025-03-19'),
            ],
        ];

        foreach ($clients as $client) {
            Client::create($client);
        }

        $this->command->info('Clients seeded successfully!');
    }
}

