<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanySettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            'company_name'              => 'Vanquish',
            'company_tagline'           => 'Empowering your mental health journey',
            'company_email'             => 'hello@vanquish.com',
            'company_phone'             => '+44 20 1234 5678',
            'company_address'           => 'London, United Kingdom',
            'company_website'           => 'https://vanquish.com',
            'pdf_header_text'           => 'Vanquish - Private & Confidential',
            'pdf_footer_text'           => 'Generated by Vanquish Platform',
            'jotform_session_notes_url' => 'https://form.jotform.com/250262657805055',
            'jotform_psg_form_url'      => 'https://form.jotform.com/250361595166056',
        ];

        foreach ($settings as $key => $value) {
            DB::table('company_settings')->updateOrInsert(
                ['key' => $key],
                ['value' => $value, 'updated_at' => now()]
            );
        }
    }
}
